FORMAT: 1A
HOST: https://apx-search.e-com.plus/api/v1/

# E-Com Plus Search API

[E-Com Plus](https://www.e-com.plus)
is a robust and flexible cloud commerce software,
totally based on REST APIs, providing a large library of methods and specifications
to deploy any digital commerce operation easly

**Search API** is our public REST interface to
[Elasticsearch](https://www.elastic.co/products/elasticsearch),
implemented as store search engine,
for faster and flexible products and terms searches
