## Group Items

### Items Object Map

The `items` type has the
[mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) above:

```
'items': {
  'dynamic_templates': [{
    'specifications': {
      'mapping': {
        'properties': {
          'text': {
            'type': 'string',
            'index': 'no'
          },
          'value': {
            'type': 'string',
            'index': 'not_analyzed'
          },
          'rgb': {
            'type': 'string',
            'index': 'not_analyzed'
          },
          'external_values': {
            'type': 'string',
            'index': 'no'
          }
        }
      },
      'path_match': 'specifications.*'
    }
  }, {
    'variations_specifications': {
      'mapping': {
        'properties': {
          'text': {
            'type': 'string',
            'index': 'no'
          },
          'value': {
            'type': 'string',
            'index': 'not_analyzed'
          },
          'rgb': {
            'type': 'string',
            'index': 'not_analyzed'
          },
          'external_values': {
            'type': 'string',
            'index': 'no'
          }
        }
      },
      'path_match': 'variations.specifications.*'
    }
  }],
  'properties': {
    'created_at': {
      'type': 'date'
    },
    'sku': {
      'type': 'string',
      'index': 'not_analyzed'
    },
    'name': {
      'type': 'string'
    },
    'slug': {
      'type': 'string',
      'index': 'no'
    },
    'permalink': {
      'type': 'string',
      'index': 'no'
    },
    'mobile_link': {
      'type': 'string',
      'index': 'no'
    },
    'status': {
      'type': 'string',
      'index': 'not_analyzed'
    },
    'available': {
      'type': 'boolean'
    },
    'visible': {
      'type': 'boolean'
    },
    'ad_relevance': {
      'type': 'byte'
    },
    'price': {
      'type': 'float'
    },
    'price_effective_date': {
      'properties': {
        'start': {
          'type': 'date'
        },
        'end': {
          'type': 'date'
        }
      }
    },
    'base_price': {
      'type': 'float'
    },
    'currency_id': {
      'type': 'string',
      'index': 'no'
    },
    'currency_symbol': {
      'type': 'string',
      'index': 'no'
    },
    'quantity': {
      'type': 'float'
    },
    'measurement': {
      'enabled': false
    },
    'condition': {
      'type': 'string',
      'index': 'not_analyzed'
    },
    'warranty': {
      'type': 'string',
      'index': 'not_analyzed'
    },
    'specifications': {
      'dynamic': true
    },
    'pictures': {
      'enabled': false
    },
    'installments': {
      'enabled': false
    },
    'discount': {
      'enabled': false
    },
    'views': {
      'type': 'integer'
    },
    'sales': {
      'type': 'integer'
    },
    'brands': {
      'properties': {
        '_id': {
          'type': 'string',
          'index': 'not_analyzed'
        },
        'name': {
          'type': 'string',
          'index': 'not_analyzed'
        },
        'slug': {
          'type': 'string',
          'index': 'no'
        }
      }
    },
    'categories': {
      'properties': {
        '_id': {
          'type': 'string',
          'index': 'not_analyzed'
        },
        'name': {
          'type': 'string',
          'index': 'not_analyzed'
        },
        'slug': {
          'type': 'string',
          'index': 'no'
        }
      }
    },
    'keywords': {
      'type': 'string'
    },
    'variations': {
      'type': 'nested',
      'properties': {
        'sku': {
          'type': 'string',
          'index': 'not_analyzed'
        },
        'name': {
          'type': 'string',
          'index': 'not_analyzed'
        },
        'price': {
          'type': 'float'
        },
        'price_effective_date': {
          'properties': {
            'start': {
              'type': 'date'
            },
            'end': {
              'type': 'date'
            }
          }
        },
        'base_price': {
          'type': 'float'
        },
        'specifications': {
          'dynamic': true
        },
        'installments': {
          'enabled': false
        },
        'discount': {
          'enabled': false
        },
        'quantity': {
          'type': 'float'
        },
        'picture_id': {
          'type': 'string',
          'index': 'no'
        }
      }
    }
  }
}
```

### Items Search [/items.json]

#### Simple Search [GET /items.json?q={field}:{value}]

ELS [URI Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html)

+ Parameters
    + field: keywords (string, required) - Valid item object property
    + value: tshirt (string, required) - Value to be searched

+ Response 200 (application/json)

        {
          "took": 1,
          "timed_out": false,
          "_shards": {
            "total": 6,
            "successful": 6,
            "skipped": 0,
            "failed": 0
          },
          "hits": {
            "total": 1,
            "max_score": 1.3862944,
            "hits": [
              {
                "_index": "100",
                "_type": "items",
                "_id": "123a5432109876543210cdef",
                "_score": 1.3862944,
                "_source": {
                  "created_at": "2017-12-01T01:00:30Z",
                  "sku": "s-MP_2B4",
                  "name": "Mens Pique Polo Shirt",
                  "slug": "mens-pique-polo-shirt",
                  "available": true,
                  "visible": true,
                  "ad_relevance": 0,
                  "views": 1131,
                  "sales": 25,
                  "price": 42.9,
                  "price_effective_date": {
                    "end": "2018-12-01T10:00:00Z"
                  },
                  "base_price": 60,
                  "quantity": 100,
                  "condition": "new",
                  "specifications": {
                    "age_group": {
                      "text": "Adult",
                      "value": "adult"
                    },
                    "gender": {
                      "text": "Male",
                      "value": "male"
                    },
                    "size": {
                      "text": "Large",
                      "value": "large"
                    },
                    "size_type": {
                      "text": "Regular",
                      "value": "regular"
                    },
                    "size_system": {
                      "text": "BR",
                      "value": "BR"
                    },
                    "material": {
                      "text": "Cotton",
                      "value": "cotton"
                    },
                    "colors": [
                      {
                        "text": "Pique",
                        "rgb": "#ff5b00"
                      }
                    ]
                  },
                  "keywords": [
                    "tshirt",
                    "t-shirt",
                    "man"
                  ],
                  "brands": [
                    {
                      "_id": "a10000000000000000000001",
                      "name": "Shirts Example",
                      "slug": "shirts-example",
                      "logo": {
                        "url": "https://mycdn.com/shirts-example.jpg",
                        "size": "100x50"
                      }
                    }
                  ],
                  "categories": [
                    {
                      "_id": "f10000000000000000000001",
                      "name": "Polo Shirts",
                      "slug": "polo"
                    }
                  ]
                }
              }
            ]
          }
        }

#### Complex Search [POST]

ELS [Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html)

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
              "query": {
                "multi_match": {
                  "query": "tshirt",
                  "fields": [
                    "name",
                    "keywords"
                  ]
                },
                "sort": [
                  {
                    "available": true
                  },
                  "_score",
                  {
                    "ad_relevance": "desc"
                  },
                  {
                    "views": "desc"
                  }
                ],
                "bool": {
                  "filter": [
                    {
                      "term": {
                        "visible": true
                      }
                    }
                  ]
                }
              }
            }

+ Response 200 (application/json)

        {
          "took": 1,
          "timed_out": false,
          "_shards": {
            "total": 6,
            "successful": 6,
            "skipped": 0,
            "failed": 0
          },
          "hits": {
            "total": 1,
            "max_score": 1.3862944,
            "hits": [
              {
                "_index": "100",
                "_type": "items",
                "_id": "123a5432109876543210cdef",
                "_score": 1.3862944,
                "_source": {
                  "created_at": "2017-12-01T01:00:30Z",
                  "sku": "s-MP_2B4",
                  "name": "Mens Pique Polo Shirt",
                  "slug": "mens-pique-polo-shirt",
                  "available": true,
                  "visible": true,
                  "ad_relevance": 0,
                  "views": 1131,
                  "sales": 25,
                  "price": 42.9,
                  "price_effective_date": {
                    "end": "2018-12-01T10:00:00Z"
                  },
                  "base_price": 60,
                  "quantity": 100,
                  "condition": "new",
                  "specifications": {
                    "age_group": {
                      "text": "Adult",
                      "value": "adult"
                    },
                    "gender": {
                      "text": "Male",
                      "value": "male"
                    },
                    "size": {
                      "text": "Large",
                      "value": "large"
                    },
                    "size_type": {
                      "text": "Regular",
                      "value": "regular"
                    },
                    "size_system": {
                      "text": "BR",
                      "value": "BR"
                    },
                    "material": {
                      "text": "Cotton",
                      "value": "cotton"
                    },
                    "colors": [
                      {
                        "text": "Pique",
                        "rgb": "#ff5b00"
                      }
                    ]
                  },
                  "keywords": [
                    "tshirt",
                    "t-shirt",
                    "man"
                  ],
                  "brands": [
                    {
                      "_id": "a10000000000000000000001",
                      "name": "Shirts Example",
                      "slug": "shirts-example",
                      "logo": {
                        "url": "https://mycdn.com/shirts-example.jpg",
                        "size": "100x50"
                      }
                    }
                  ],
                  "categories": [
                    {
                      "_id": "f10000000000000000000001",
                      "name": "Polo Shirts",
                      "slug": "polo"
                    }
                  ]
                }
              }
            ]
          }
        }
