## Group Terms

### Terms Object Map

The `terms` type has the
[mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) above:

```
'terms': {
  'properties': {
    'date': {
      'type': 'date'
    },
    'term': {
      'type': 'string'
    },
    'results': {
      'type': 'short'
    },
    'count': {
      'type': 'integer'
    }
  }
}
```

### Terms Search [/terms.json]

#### Simple Search [GET /terms.json?q={field}:{value}]

ELS [URI Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html)

+ Parameters
    + field: `term` (string, required) - Valid term object property
    + value: `t-shirt` (string, required) - Value to be searched

+ Response 200 (application/json)

        {
        }

#### Complex Search [POST]

ELS [Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html)

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
            }

+ Response 200 (application/json)

        {
        }
